set -g default-terminal "xterm-256color"
set -g mouse on
bind-key -T root MouseDown1Pane send-keys -M
bind-key -T root MouseUp1Pane send-keys -M
bind-key -T root MouseDrag1Pane send-keys -M
bind-key -T root MouseDragEnd1Pane send-keys -M
bind-key -T root MouseDown2Pane send-keys -M
bind-key -T root MouseUp2Pane send-keys -M
bind-key -T root MouseDown3Pane send-keys -M
bind-key -T root MouseUp3Pane send-keys -M

unbind-key -T root S-Left
unbind-key -T root S-Right
unbind-key -T root S-Up
unbind-key -T root S-Down

